package main;

import config.MapConfig;
import controller.GameController;
import controller.KeyController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class HotkeyDebug {
    public JPanel cp;
    private JButton button1;


    public HotkeyDebug() {
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        cp = new JPanel();
        cp.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cp;
    }
}

class HotkeyTestGui {
//    public static void main(String[] args) {
//        JFrame frame = new JFrame("ColorWorld");
//        frame.setContentPane(new HotkeyDebug().cp);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
////        frame.pack();
//        frame.setSize(400,400);
//        frame.setVisible(true);
//        GameController gameController=new GameController(new MapConfig());
////        frame.addKeyListener(new controller.KeyController(gameController));
//        //TODO: copy this keycontroller to main window
//    }
}